# Generated by Django 3.2.15 on 2022-08-27 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='office_spaces',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('office_name', models.CharField(max_length=50)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myspace.category')),
            ],
        ),
        migrations.CreateModel(
            name='meeting_rooms',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('meeting_name', models.CharField(max_length=50)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myspace.category')),
            ],
        ),
    ]
