# Generated by Django 3.2.15 on 2022-08-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspace', '0003_auto_20220827_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office_spaces',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
