# Generated by Django 3.2.15 on 2022-08-27 20:59

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('myspace', '0004_alter_office_spaces_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting_rooms_booked',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting_rooms_booked',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='office_spaces_booked',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='office_spaces_booked',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
