# Generated by Django 3.2.15 on 2022-08-27 21:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myspace', '0006_auto_20220827_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office_spaces_booked',
            old_name='end_time',
            new_name='end_datetime',
        ),
        migrations.RenameField(
            model_name='office_spaces_booked',
            old_name='start_time',
            new_name='start_datetime',
        ),
        migrations.RemoveField(
            model_name='meeting_rooms_booked',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='meeting_rooms_booked',
            name='start_time',
        ),
        migrations.AddField(
            model_name='meeting_rooms_booked',
            name='end_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting_rooms_booked',
            name='start_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
