# Generated by Django 3.2.15 on 2022-08-27 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myspace', '0008_auto_20220827_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting_rooms_booked',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='meeting_rooms_booked',
            name='start_datetime',
        ),
        migrations.RemoveField(
            model_name='office_spaces_booked',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='office_spaces_booked',
            name='start_datetime',
        ),
    ]
