# Generated by Django 3.2.15 on 2022-08-27 21:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myspace', '0010_alter_office_spaces_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='office_spaces_booked',
            name='end_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='office_spaces_booked',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
