# Generated by Django 3.2.15 on 2022-09-02 23:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myspace', '0011_auto_20220827_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_type', models.CharField(default='Small', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='meeting_rooms',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='meeting_rooms_booked',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='office_spaces',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='office_spaces_booked',
            name='category_id',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.AddField(
            model_name='meeting_rooms',
            name='office_type',
            field=models.ForeignKey(null=True,on_delete=django.db.models.deletion.CASCADE, to='myspace.office_types'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting_rooms_booked',
            name='office_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myspace.office_types'),
        ),
        migrations.AddField(
            model_name='office_spaces',
            name='office_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myspace.office_types'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='office_spaces_booked',
            name='office_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myspace.office_types'),
        ),
    ]
