# Generated by Django 3.2.15 on 2022-09-04 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myspace', '0012_auto_20220902_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting_rooms',
            name='office_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myspace.office_types'),
        ),
        migrations.AlterField(
            model_name='office_spaces',
            name='office_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myspace.office_types'),
        ),
    ]
