# Generated by Django 3.2.15 on 2022-09-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspace', '0013_auto_20220904_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='office_types',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='office_types',
            name='office_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
